name: WorldEditEntities
version: '1.0'
main: com.bocktom.worldEditEntities.WorldEditEntitiesPlugin
api-version: '1.21'
commands:
  /countentities:
    description: Count entities in the selected region.
    usage: /countentities
  /countall:
    description: Count all entities and tile entities in the world.
    usage: /countall
  /counttileentities:
    description: Count tile entities in the selected region.
    usage: /counttileentities
  /countstop:
    description: Stop the ongoing entity counting process.
    usage: /countstop
permissions:
  worldeditentities.count:
    description: Allows the use of /countentities command.
    default: op
depend:
    - FastAsyncWorldEdit