name: WorldEditEntityScanner
version: '1.0'
author: Tommm
main: com.bocktom.worldeditentityscanner.WorldEditEntityScannerPlugin
api-version: '1.21'
commands:
  /scanentities:
    description: Count entities in the selected region.
    usage: //scanentities
    permission: worldeditentityscanner.use
  /scantileentities:
    description: Count tile entities in the selected region.
    usage: //scantileentities
    permission: worldeditentityscanner.use
  /scanall:
    description: Count all entities and tile entities in the world.
    usage: //scanall
    permission: worldeditentityscanner.use
  /scanstop:
    description: Stop the ongoing entity counting process.
    usage: //scanstop
    permission: worldeditentityscanner.use
permissions:
  worldeditentityscanner.use:
    description: Allows the use of all scan commands.
    default: op
depend:
    - FastAsyncWorldEdit